export const FILL_ME = "FILL_ME";
export const LOADING_ME = "LOADING_ME";
export const ERROR_ME = "ERROR_ME";

export const FILL_AUTHORS = "FILL_AUTHORS";
export const LOADING_AUTHORS = "LOADING_AUTHORS";
export const ERROR_AUTHORS = "ERROR_AUTHORS";

export const FILL_AUTHOR = "FILL_AUTHOR";
export const LOADING_AUTHOR = "LOADING_AUTHOR";
export const ERROR_AUTHOR = "ERROR_AUTHOR";

export const FILL_STORIES = "FILL_STORIES";
export const LOADING_STORIES = "LOADING_STORIES";
export const ERROR_STORIES = "ERROR_STORIES";

export const FILL_MY_STORIES = "FILL_MY_STORIES";
export const LOADING_MY_STORIES = "LOADING_MY_STORIES";
export const ERROR_MY_STORIES = "ERROR_MY_STORIES";

export const FILL_HEARTED_STORIES = "FILL_HEARTED_STORIES";
export const LOADING_HEARTED_STORIES = "LOADING_HEARTED_STORIES";
export const ERROR_HEARTED_STORIES = "ERROR_HEARTED_STORIES";

export const FILL_AUTHOR_STORIES = "FILL_AUTHOR_STORIES";
export const LOADING_AUTHOR_STORIES = "LOADING_AUTHOR_STORIES";
export const ERROR_AUTHOR_STORIES = "ERROR_AUTHOR_STORIES";

export const FILL_RANDOM_STORY = "FILL_RANDOM_STORY";
export const LOADING_RANDOM_STORY = "LOADING_RANDOM_STORY";
export const ERROR_RANDOM_STORY = "ERROR_RANDOM_STORY";

export const FILL_STORY = "FILL_STORY";
export const LOADING_STORY = "LOADING_STORY";
export const ERROR_STORY = "ERROR_STORY";

export const FILL_COMMENTS = "FILL_COMMENTS";
export const LOADING_COMMENTS = "LOADING_COMMENTS";
export const ERROR_COMMENTS = "ERROR_COMMENTS";

export const FILL_COMMENT = "FILL_COMMENT";
export const LOADING_COMMENT = "LOADING_COMMENT";
export const ERROR_COMMENT = "ERROR_COMMENT";

export const FILL_AUTHORIZATION_HEADER = "FILL_AUTHORIZATION_HEADER";
export const LOADING_AUTHORIZATION_HEADER = "LOADING_AUTHORIZATION_HEADER";
export const ERROR_AUTHORIZATION_HEADER = "ERROR_AUTHORIZATION_HEADER";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
